src: 
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/UFAL.med.en-fr.train.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/ECB.en-fr.train.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/IT.en-fr.train.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/JRC-Acquis.en-fr.train.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/Tanzil.en-fr.train.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/TED2013.en-fr.train.en
tgt: 
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/UFAL.med.en-fr.train.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/ECB.en-fr.train.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/IT.en-fr.train.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/JRC-Acquis.en-fr.train.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/Tanzil.en-fr.train.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/TED2013.en-fr.train.fr
domain:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
eval_src:
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/UFAL.med.en-fr.dev.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/ECB.en-fr.dev.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/IT.en-fr.dev.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/JRC-Acquis.en-fr.dev.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/Tanzil.en-fr.dev.en
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/TED2013.en-fr.dev.en
eval_ref:
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/UFAL.med.en-fr.dev.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/ECB.en-fr.dev.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/IT.en-fr.dev.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/JRC-Acquis.en-fr.dev.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/Tanzil.en-fr.dev.fr
        - /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/TED2013.en-fr.dev.fr
eval_domain:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
src_vocab: /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/vocab.en_fr
tgt_vocab: /gpfsdswork/projects/rech/sfz/utt84zy/clean_data/vocab.en_fr

model_dir: /gpfsdsstore/projects/rech/sfz/utt84zy/models/config_205

batch_train_size: 4096
batch_meta_train_size: 4096
batch_meta_test_size: 4096
batch_type: tokens
experiment: residualv5
accumulation_step: 1
train_steps: 200000
step_duration: 8
stopping_gradient: true
ADAP_layer_stopping_gradient: false
initializer: 
ADAP_activity_regularizing: false
num_domains: 6
num_domain_units: 1024
layer_activity_regularization_loss_scale:
        - 0.0001
        - 0.0001
        - 0.0001
        - 0.0001
        - 0.0001
        - 0.0001
output_activity_regularization_loss_scale: 
        - 0.0001
        - 0.0001
        - 0.0001
        - 0.0001
        - 0.0001
        - 0.0001
meta_train_lr: 0.0001
picking_prob: Natural
